package main

import (
	"gostories/engine"
	"gostories/gen/items/features"
	"gostories/gen/items/items"
	"gostories/things"
)

func main() {
	catRoom := catRoom()
	storeRoom := storeRoom()
	kitchen := kitchenRoom()

	// Add Exits
	catRoomToStockRoomExit := things.Exit{
		To:   &storeRoom,
		From: &catRoom,
	}
	storeRoomToCatRoomExit := things.Exit{
		To:   &catRoom,
		From: &storeRoom,
	}
	storeRoomToKitchenExit := things.Exit{
		To:   &kitchen,
		From: &storeRoom,
	}
	kitchenToStoreRoomExit := things.Exit{
		To:   &storeRoom,
		From: &kitchen,
	}
	catRoom.Exits[things.West] = catRoomToStockRoomExit
	storeRoom.Exits[things.East] = storeRoomToCatRoomExit
	storeRoom.Exits[things.North] = storeRoomToKitchenExit
	kitchen.Exits[things.South] = kitchenToStoreRoomExit

	// TODO: Perhaps also autogenerate the code for adding Items to Areas (currently only the reveal
	// trigger on a Feature is autogenerated.)
	// Add item
	collar := items.Item_Collar
	collar.Hide()
	storeRoom.Items = append(storeRoom.Items, collar)

	sardines := items.Item_Sardines
	sardines.Hide()
	kitchen.Items = append(kitchen.Items, sardines)

	stage := engine.Stage{}
	stage.Start(catRoom)
}

// TODO move area construction out of main
func catRoom() things.Area {
	return things.Area{
		Look:   "You are in a small room, which is totally empty apart from a fat ginger cat, and a door to the west.",
		Beings: []things.Being{things.NewBubbles()},
		Exits:  make(map[things.Direction]things.Exit),
		Items:  []things.Item{},
	}
}

func storeRoom() things.Area {
	return things.Area{
		Look:   "You are in some kind of stockroom. There is one shelf stacked high against one wall, across from the entrance.",
		Beings: []things.Being{},
		Exits:  make(map[things.Direction]things.Exit),
		Items:  []things.Item{},
		Features: []things.Feature{
			features.Feature_Shelf,
		},
	}
}

func kitchenRoom() things.Area {
	return things.Area{
		Look:   "You are in a cramped kitchen, there is a fridge on the far side of the wall and one cupboard.",
		Beings: []things.Being{},
		Exits:  make(map[things.Direction]things.Exit),
		Items:  []things.Item{},
		Features: []things.Feature{
			features.Feature_Fridge,
		},
	}
}
