package parser

type void struct{}

var member void

var prepositions = map[string]void{
	"about":      member,
	"below":      member,
	"excepting":  member,
	"off":        member,
	"toward":     member,
	"above":      member,
	"beneath":    member,
	"for":        member,
	"on":         member,
	"under":      member,
	"across":     member,
	"besides":    member,
	"beside":     member,
	"from":       member,
	"onto":       member,
	"underneath": member,
	"after":      member,
	"between":    member,
	"in":         member,
	"out":        member,
	"until":      member,
	"against":    member,
	"outside":    member,
	"up":         member,
	"along":      member,
	"inside":     member,
	"over":       member,
	"upon":       member,
	"among":      member,
	"by":         member,
	"past":       member,
	"around":     member,
	"with":       member,
	"at":         member,
	"into":       member,
	"within":     member,
	"down":       member,
	"like":       member,
	"through":    member,
	"without":    member,
	"before":     member,
	"during":     member,
	"near":       member,
	"throughout": member,
	"behind":     member,
	"except":     member,
	"of":         member,
	"to":         member,
}
