package parser

type void struct{}

var member void

var articles = map[string]void{
	"the": member,
	"a":   member,
	"an":  member,
}

var prepositions = map[string]void{
	"about":      member,
	"below":      member,
	"excepting":  member,
	"off":        member,
	"toward":     member,
	"above":      member,
	"beneath":    member,
	"for":        member,
	"on":         member,
	"under":      member,
	"across":     member,
	"besides":    member,
	"beside":     member,
	"from":       member,
	"onto":       member,
	"underneath": member,
	"after":      member,
	"between":    member,
	"in":         member,
	"out":        member,
	"until":      member,
	"against":    member,
	"outside":    member,
	"up":         member,
	"along":      member,
	"inside":     member,
	"over":       member,
	"upon":       member,
	"among":      member,
	"by":         member,
	"past":       member,
	"around":     member,
	"with":       member,
	"at":         member,
	"into":       member,
	"within":     member,
	"down":       member,
	"like":       member,
	"through":    member,
	"without":    member,
	"before":     member,
	"during":     member,
	"near":       member,
	"throughout": member,
	"behind":     member,
	"except":     member,
	"of":         member,
	"to":         member,
}

var conjunctions = map[string]void{
	"for":       member,
	"and":       member,
	"nor":       member,
	"but":       member,
	"or":        member,
	"yet":       member,
	"so":        member,
	"both":      member,
	"either":    member,
	"neither":   member,
	"not":       member,
	"only":      member,
	"whether":   member,
	"after":     member,
	"although":  member,
	"as":        member,
	"if":        member,
	"because":   member,
	"before":    member,
	"lest":      member,
	"now":       member,
	"once":      member,
	"since":     member,
	"supposing": member,
	"that":      member,
	"than":      member,
	"though":    member,
	"till":      member,
	"unless":    member,
	"until":     member,
	"when":      member,
	"whenever":  member,
	"where":     member,
	"whereas":   member,
	"wherever":  member,
	"while":     member,
}
